import Config
# Configure your database
config :time_manager, TimeManager.Repo,
  username: System.get_env("PGUSER"),  # Nom d'utilisateur de la base de données
  password: System.get_env("PGPASSWORD"),  # Mot de passe de la base de données
  hostname: "dpg-cse406e8ii6s738sek00-a.oregon-postgres.render.com",  # Nom d'hôte complet pour la base de données
  database: System.get_env("PGDATABASE"),  # Nom de la base de données
  port: String.to_integer(System.get_env("PGPORT") || "5432"),  # Port (assure-toi que c'est un entier)
  stacktrace: true,  # Affiche la pile d'appels en cas d'erreur
  ssl: true,  # Active SSL pour la connexion
  show_sensitive_data_on_connection_error: true,  # Affiche les données sensibles lors d'erreurs de connexion
  pool_size: 10,  # Taille du pool de connexions
  url: System.get_env("DATABASE_URL") <> "?sslmode=require"  # URL de connexion

# Configurer l'endpoint Phoenix
config :time_manager, TimeManagerWeb.Endpoint,
  url: [host: "back-8h8p.onrender.com", port: 443],  # URL de l'endpoint
  cache_static_manifest: "priv/static/cache_manifest.json",  # Manifest pour les fichiers statiques
  check_origin: ["//back-8h8p.onrender.com"],  # Vérification de l'origine pour les requêtes CORS
  server: true  # Active le serveur web
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# config :time_manager, TimeManagerWeb.Endpoint,
#   # Binding to loopback ipv4 address prevents access from other machines.
#   # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
#   http: [ip: {0, 0, 0, 0}, port: 4000],
#   check_origin: false,
#   code_reloader: true,
#   debug_errors: true,
#   secret_key_base: "3ceAZL09T4E0gp5WvQBXUEgNYjEqtnWRk/VxuAzdRqOLpDjYXIWlug2DAPRtw7ja"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :time_manager, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
